### ISSUE TITLE
Style image directive

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#1110]
I noticed this while working on #385.

```rst
.. image:: /m/community/awards/frank-willison/kuchling.jpg
   :align: right
```

should be styled as

```css
img.align-right {
    float:right;
}
```
