### ISSUE TITLE
Sidebar does not render correctly in a PEP

### ISSUE THREAD

**Issue by abalkin** [python/pythondotorg#808]
I tried to place the graphics in a sidebar similar top the one we have on the "turtle" documentation page:
https://docs.python.org/3.6/library/turtle.html.  However, it did not work as I expected:https://www.python.org/dev/peps/pep-0495/#abstract. 

[Berker Peksağ]

The markup is correct, so I think this can be fixed with a simple CSS work.

**Comment by abalkin** [comment]
Here are the relevant definitions from https://docs.python.org/3.6/_static/basic.css

``` css
/* -- sidebars -------------------------------------------------------------- */

div.sidebar {
    margin: 0 0 0.5em 1em;
    border: 1px solid #ddb;
    padding: 7px 7px 0 7px;
    background-color: #ffe;
    width: 40%;
    float: right;
}

p.sidebar-title {
    font-weight: bold;
}
```

I think the key setting is `float: right;`.
