### ISSUE TITLE
SIG page is missing the list of SIGs

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#89]
The page (http://python.org/community/sigs/) says:

"""
Below is the list of currently active Python SIGs, with links to their resources. The link in the first column directs you to the SIG's home page: a page with more information about the SIG. The links in the "Info" column direct you to the SIG's archives, and to the SIG's Mailman page, which you can use to subscribe or unsubscribe yourself and to change your subscription options.
"""

but is missing the table that's available on the old page:

http://legacy.python.org/community/sigs/

**Comment by ned-deily** [comment]
cpgray notes in #235: "The problem is repeated on the page of retired SIGs /community/sigs/retired/."

Also, the content of the individual sig pages is rendered incorrectly as reST rather than html.

Looking at the legacy site source, it appears the sig section was managed as some custom templates and data fed from a simple yaml data file.  One way to deal with this on the new site would be to write a SIG app to manage the data for each SIG and then automatically generate the current and retired pages and the individual pages for each SIG.  Until that happens, someone could paste the generated content from the top-level legacy pages as html and change the "content markup type" of each sig page.

**Comment by ned-deily** [comment]
Here's the current yaml file from the legacy website.  There's also a retired file. So, for a SIG's model, I think we'd want most of the items from the legacy object plus a _status_ field (**current**, **retired**) and a _long description_ text field which contains the content (html or reST) from the particular SIG's _content.ht_ page.

``` yaml
--- !fragment
# Type of template to use
template: sigindex.html

# The data to pass to the template
global:
  sigs:
   -
    dir: capi-sig/
    id: capi-sig
    link: mailto:cbarton@metavr.com
    name: Campbell Barton
    description: Support for Using the Python/C API
    details: 
   -
    dir: c++-sig/
    id: cplusplus-sig
    link: mailto:rwgk@yahoo.com
    name: Ralf W. Grosse-Kunstleve
    description: Development of Python/C++ bindings
    details: 
   -
    dir: db-sig/
    id: db-sig
    link: mailto:andy47@halfcooked.com
    name: Andy Todd
    description: Databases
    details: Common tabular database API
   -
    dir: distutils-sig/
    id: distutils-sig
    link: mailto:distutils-sig@msg.amk.ca
    name: A.M. Kuchling
    description: Packaging and build tools.
    details:
   -
    dir: doc-sig/
    id: doc-sig
    link: mailto:fdrake@acm.org
    name: Fred Drake
    description: Documentation
    details: Doc tools and content
   -
    dir: edu-sig/
    id: edu-sig
    link: mailto:wilson@visi.com
    name: Timothy Wilson
    description: Python in Education
    details: Computer Programming for Everybody
   -
    dir: email-sig
    id: email-sig
    link: mailto:barry@python.org
    name: Barry Warsaw
    description: email package SIG
    details: Design and implement v3.0 of the email package for Python 2.4
   -
    dir: i18n-sig/
    id: i18n-sig
    link: mailto:andy@robanal.demon.co.uk
    name: Andy Robinson
    description: Internationalization
    details: Localization
   -
    dir: image-sig/
    id: image-sig
    link: mailto:fredrik@pythonware.com
    name: Fredrik Lundh
    description: Image Processing
    details:
   -
    dir: import-sig/
    id: import-sig
    link: mailto:barry@python.org
    name: Barry Warsaw
    description: Import SIG
    details: Landing PEP 382 and refactoring import.c and importlib
   -
    dir: meta-sig/
    id: meta-sig
    link: mailto:barry@python.org
    name: Barry Warsaw
    description: SIG about the SIGs
    details: Discussion about SIGs - creating, retiring and so on.
   -
    dir: pythonmac-sig/
    id: pythonmac-sig
    link: mailto:Jack.Jansen@cwi.nl
    name: Jack Jansen
    description: On Apple Macintosh
    details: 
   -
    dir: stdlib-sig/
    id: stdlib-sig
    link: http://barry.warsaw.us
    name: Barry Warsaw
    description: Development, improvement, and maintenance of the Python standard library.
    details: 
   -
    dir: uls-sig/
    id: uls-sig
    link: http://oubiwann.blogspot.com/
    name: Duncan McGreggor
    description: Ultra Large-Scale systems and how such systems relate to Python.
    details: 
   -
    dir: web-sig/
    id: web-sig
    link: http://www2.parc.com/istl/members/janssen/
    name: Bill Janssen
    description: Web-related Enhancements
    details: 
   -
    dir: xml-sig/
    id: xml-sig
    link: mailto:r.salz@verizon.net
    name: Rich Salz
    description: XML Processing
    details: 

```
